export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const APP_HAS_LOADED = 'APP_HAS_LOADED';
export const SCREEN_CHANGE = 'SCREEN_CHANGE';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';